# Generated by Django 4.2.7 on 2023-12-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='accountLvl',
            field=models.IntegerField(default=1),
        ),
    ]
