# Generated by Django 4.2.7 on 2023-12-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_accountlvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatspeed', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('accountLvl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login.accountlevel')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
